

export const GET_MUSIC_REC_REQUEST ="GET_MUSIC_REC_REQUEST"


export const GET_MUSIC_REC_SUCCESS="GET_MUSIC_REC_SUCCESS"


export const GET_MUSIC_REC_FAILURE ="GET_MUSIC_REC_FAILURE"




export const UPDATE_MUSIC_REC_REQUEST ="UPDATE_MUSIC_REC_REQUEST"


export const UPDATE_MUSIC_REC_SUCCESS="UPDATE_MUSIC_REC_SUCCESS"


export const UPDATE_MUSIC_REC_FAILURE ="UPDATE_MUSIC_REC_FAILURE"
